### ISSUE TITLE
Hubs v0.1 – Power BI on CM exports

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#1]
## 🚀 Goal
Create an ARM template that configures a new Cost Management export to ADLS and generates a Power BI report that can work against that dataset. The template should also include a Data Factory pipeline to delete old files when data is exported each day.

## 📋 Tasks
```[tasklist]
### v0.0.1 - finops-hub template ([discuss](https://github.com/microsoft/cloud-hubs/discussions/44))
- [x] #5
- [x] Generate aka.ms links for all report pages
- [x] #21
- [x] Split out 0.1 into smaller releases
- [ ] https://github.com/microsoft/cloud-hubs/issues/24
- [ ] https://github.com/microsoft/cloud-hubs/issues/29
- [ ] https://github.com/microsoft/cloud-hubs/issues/37
- [ ] https://github.com/microsoft/cloud-hubs/issues/51
- [ ] https://github.com/microsoft/cloud-hubs/issues/23
- [ ] https://github.com/microsoft/cloud-hubs/issues/58
- [ ] https://github.com/microsoft/cloud-hubs/issues/65
- [ ] https://github.com/microsoft/cloud-hubs/issues/34
- [ ] https://github.com/microsoft/cloud-hubs/issues/59
- [ ] https://github.com/microsoft/cloud-hubs/issues/64
- [ ] https://github.com/microsoft/cloud-hubs/issues/124
- [ ] https://github.com/microsoft/cloud-hubs/issues/126
- [ ] https://github.com/microsoft/cloud-hubs/issues/125
- [ ] https://github.com/microsoft/cloud-hubs/issues/63
- [x] Test deployment
- [ ] https://github.com/microsoft/cloud-hubs/issues/144
- [ ] #26
- [x] Sync feature branches
- [x] Create new release
- [x] Release maintenance
- [x] Address all feedback from the release discussion
```

```[tasklist]
### v0.0.2 - Self-managed exports ([discuss](https://github.com/microsoft/cloud-hubs/discussions/45))
- [ ] https://github.com/microsoft/cloud-hubs/issues/168
- [ ] https://github.com/microsoft/finops-toolkit/issues/187
- [ ] https://github.com/microsoft/finops-toolkit/issues/186
- [x] Ingest data across hub instances
- [x] Add actual cost data
- [x] Historical data refresh (rerating)
- [ ] https://github.com/microsoft/cloud-hubs/issues/60
- [ ] https://github.com/microsoft/cloud-hubs/issues/67
- [ ] https://github.com/microsoft/cloud-hubs/issues/130
- [ ] Create pre/post-process scripts
- [ ] Setup PR build
- [ ] Power BI linked reports/datasets
- [x] Make sure all resources are tagged
- [ ] Address all feedback from the release discussion
```

```[tasklist]
### v0.0.3 - Additional datasets ([discuss](https://github.com/microsoft/cloud-hubs/discussions/74))
- [ ] https://github.com/microsoft/cloud-hubs/issues/83
- [ ] Static website to manage config
- [ ] Address all feedback from the release discussion
```

```[tasklist]
### v0.1 - FOCUS schema ([discuss](https://github.com/microsoft/cloud-hubs/discussions/61))
- [ ] Add normalization as a template parameter
- [ ] https://github.com/microsoft/cloud-hubs/issues/76
- [ ] https://github.com/microsoft/cloud-hubs/issues/81
- [ ] Update Power BI reports to use new schema
- [ ] https://github.com/microsoft/cloud-hubs/issues/43
- [x] Add ADX cluster/database
- [x] Define union schema in parquet
- [x] Add ADX union table
- [ ] Add ADX FOCUS table and update policy
- [ ] Add EventGrid trigger to ingest data into ADX
- [ ] Change ADF to move parquet to archive/raw container
- [ ] Address all feedback from the release discussion
```

```[tasklist]
### Stretch
- [ ] https://github.com/microsoft/cloud-hubs/issues/38
- [ ] Do we have a way to protect from people exporting data multiple times using parent scopes? At a minimum, cover this as a warning in docs.
- [ ] Create feature proposal for deltas in Cost Management exports
- [ ] Create feature proposal for how to deploy from Cost Management
- [ ] Create feature proposal for Power BI code reuse across reports
- [ ] Create feature proposal for Power BI versioning and targeted code reviews
- [ ] Management groups with unsupported subscriptions (where exports don't work today)
- [ ] Data freshness setting (refresh rate; currently 24h)
- [ ] Commitment purchases (or actual+amortized as one)
- [ ] Forecasting
- [ ] Optimize storage with deltas
- [ ] Post-ingestion validation
- [ ] Historical data refresh
- [ ] Cross-channel credit handling (e.g., EA MC, MACC)
- [ ] Cost Management portal integration
- [ ] Publish to Azure Marketplace
- [ ] Hourly data via UsageAggregates x Pricesheet
- [ ] Unsupported subscriptions (classic sponsorship/CSP) via UsageAggregates x Pricesheet
- [ ] Consumption Insights connector migration support
- [ ] https://github.com/microsoft/finops-toolkit/issues/259
- [ ] AWS support
- [ ] GCP support
```

## 🙋‍♀️ Ask for the community

We'd love to get your feedback! Please leave any questions, comments, or change requests in the release discussions at the bottom of each task list above. We'll try to close each of those out before we finalize the release.

**Comment by flanakin** [comment]
Moving to projects
