### ISSUE TITLE
[Fabric] Ingest data into Microsoft Fabric

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#1009]
## 📝 Scenario
As a **FinOps practitioner**, I need to **ingest data into Microsoft Fabric** in order to **leverage Fabric reporting, alerting, and AI capabilities**

## 💎 Solution
Ingest data into Microsoft Fabric and extend the existing FinOps toolkit reporting to Fabric.

## 📋 Tasks
- [ ] ~Address the data ingestion bug with tags~
- [x] Validate documentation for connecting to FinOps hubs
- [ ] ~Update Power BI reports to connect to a lakehouse~
- [x] Update Power BI reports to connect to Fabric RTI
- [ ] Automate workspace setup/configuration
- [x] Add documentation to support Fabric setup
- [x] Connect Fabric to FinOps hubs Kusto instance (when ready)

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by flanakin** [comment]
We decided to implement this via Real-Time Intelligence for improved performance and capabilities. This also aligns with our non-Fabric offering for more reuse.
