### ISSUE TITLE
Toolkit v1.0 – Basic Cost Management automation

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#104]
## 📝 Scenario
As a **FinOps practitioner**, I need to **automate the deployment of Cost Management resources** in order to **streamline onboarding**

## 🚀 Goal
Publish modules to the Bicep Registry for all Cost Management features to simplify template creation.

## 📋 Tasks

```[tasklist]
### v0.1 – Basics ([discuss](https://github.com/microsoft/cloud-hubs/discussions/103))
- [ ] https://github.com/microsoft/cloud-hubs/issues/116
- [ ] #107 
- [ ] #1 
- [ ] Address all feedback from the release discussion
```

```[tasklist]
### v0.2 – Bicep modules for billing accounts ([discuss](https://github.com/microsoft/cloud-hubs/discussions/105))
- [ ] Cost allocation rules bicep module for billing accounts
- [ ] Cost details bicep module for billing accounts (TBD)
- [ ] Exports bicep module for billing accounts
- [ ] Reservation details bicep module for billing accounts (TBD)
- [ ] Scheduled actions bicep for billing accounts
- [ ] Settings bicep module for billing accounts
- [ ] Views bicep module for billing accounts
- [ ] Address all feedback from the release discussion
```

```[tasklist]
### v0.3 – Scripts for resources ([discuss](https://github.com/microsoft/cloud-hubs/discussions/106))
- [ ] Review gaps in PowerShell and CLI scripts
- [ ] Brainstorm script generation for PowerShell and CLI
- [ ] Cost allocation rules scripts
- [ ] Cost details scripts
- [ ] Exports scripts
- [ ] Reservation details scripts
- [ ] Scheduled actions scripts
- [ ] Settings scripts
- [ ] Views scripts
- [ ] Address all feedback from the release discussion
```

```[tasklist]
### v0.4 – Scripts for read-only APIs ([discuss](https://github.com/microsoft/cloud-hubs/discussions/107))
- [ ] Review gaps in PowerShell and CLI scripts
- [ ] Advisor recommendations scripts
- [ ] Alerts scripts
- [ ] Benefit recommendations scripts
- [ ] Benefit utilization summaries scripts
- [ ] Dimensions scripts (TBD)
- [ ] Forecast scripts
- [ ] Insights scripts
- [ ] Pricesheet scripts
- [ ] Query scripts
- [ ] Address all feedback from the release discussion
```

## 🙋‍♀️ Ask for the community

We'd love to get your feedback! Please leave any questions, comments, or change requests in the release discussions at the bottom of each task list above. We'll try to close each of those out before we finalize the release.

**Comment by flanakin** [comment]
Moving to projects
