### ISSUE TITLE
Add a query for centrally managed Azure Hybrid Benefit for SQL Server

### ISSUE THREAD

**Issue by arthurclares** [microsoft/finops-toolkit#1208]
## 📝 Scenario
As a FinOps practicioner, I need to use the COW as a central place to manage my AHB benefits. Today, it doesn't cover licenses enabled through Centrally Managed AHB.

https://learn.microsoft.com/en-us/azure/cost-management-billing/scope-level/create-sql-license-assignments#track-assigned-license-use

https://learn.microsoft.com/en-us/azure/cost-management-billing/scope-level/transition-existing

https://learn.microsoft.com/en-us/azure/cost-management-billing/scope-level/overview-azure-hybrid-benefit-scope

Centrally managing Azure Hybrid Benefit at a scope-level covers the following common Azure SQL resources:

SQL Databases
SQL Managed Instances
SQL Elastic Pools
SQL Server on Azure VMs

## 💎 Solution
Add a query to the AHB tab to check for SQL VMs where the benefit was enabled through Centrally Managed AHB .

## 📋 Tasks
```[tasklist]
### Required tasks
- [ ] Add the query
- [ ] Run tests
- [ ] Update the Advisor workbook
```

```[tasklist]
### Stretch goals
- [ ] TODO: Add Arc resources
```

## ℹ️ Additional context
TODO: Add any other context or screenshots about the change request, including alternative solutions you considered and why you ruled them out.

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.
