### ISSUE TITLE
PowerShell module v1.0

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#123]
## 🚀 Goal
Create a PowerShell module that runs toolkit scripts and deploys/manages toolkit solutions.

## 📋 Tasks

```[tasklist]
### PowerShell for Hubs v0.0.1
- [ ] https://github.com/microsoft/finops-toolkit/issues/248
- [ ] https://github.com/microsoft/finops-toolkit/issues/247
- [ ] #145
- [ ] https://github.com/microsoft/finops-toolkit/issues/249
- [ ] https://github.com/microsoft/finops-toolkit/issues/238
- [ ] https://github.com/microsoft/finops-toolkit/issues/233
- [ ] https://github.com/microsoft/finops-toolkit/issues/231
- [ ] https://github.com/microsoft/finops-toolkit/issues/240
- [ ] https://github.com/microsoft/finops-toolkit/issues/237
- [ ] https://github.com/microsoft/finops-toolkit/issues/241
- [ ] https://github.com/microsoft/finops-toolkit/issues/242
- [ ] https://github.com/microsoft/finops-toolkit/issues/235
- [x] [PowerShell] Create a PowerShell Gallery account for publishing
- [ ] https://github.com/microsoft/finops-toolkit/issues/239
- [ ] #146
- [ ] https://github.com/microsoft/finops-toolkit/issues/251
- [ ] https://github.com/microsoft/finops-toolkit/issues/252
- [ ] https://github.com/microsoft/finops-toolkit/issues/250
- [ ] https://github.com/microsoft/finops-toolkit/issues/253
- [ ] https://github.com/microsoft/finops-toolkit/issues/257
- [ ] https://github.com/microsoft/finops-toolkit/issues/258
```

```[tasklist]
### PowerShell for Hubs v0.0.2
- [ ] https://github.com/microsoft/finops-toolkit/issues/236
- [ ] https://github.com/microsoft/finops-toolkit/issues/267
- [ ] https://github.com/microsoft/finops-toolkit/issues/246
- [ ] https://github.com/microsoft/finops-toolkit/issues/385
- [ ] https://github.com/microsoft/finops-toolkit/issues/386
- [ ] https://github.com/microsoft/finops-toolkit/issues/387
- [ ] https://github.com/microsoft/finops-toolkit/issues/388
```

```[tasklist]
### PowerShell for workbooks
- [ ] [PowerShell] Deploy-FinOpsWorkbook function to deploy workbooks
- [ ] [PowerShell] Remove-FinOpsWorkbook function to delete workbooks
```

```[tasklist]
### PowerShell for automation
- [ ] [PowerShell] Functions to manage CM scheduled actions
- [ ] [PowerShell] Functions to manage CM budgets
- [ ] [PowerShell] Functions to manage CM views
- [ ] [PowerShell] Functions to manage CM exports
- [ ] [PowerShell] Functions to manage CM allocation rules
- [ ] [PowerShell] Functions to manage CM tag inheritance
- [ ] [PowerShell] Functions to manage hierarchical budgets in CM
- [ ] [PowerShell] Functions to manage seasonal budgets in CM
- [ ] [PowerShell] Functions to manage "forecast" budgets in CM
- [ ] [PowerShell] Get-FinOpsCostDetails function
- [ ] [PowerShell] Get-FinOpsPriceSheet function
- [ ] [PowerShell] Query-FinOpsCostDetails function (includes forecast)
- [ ] [PowerShell] Get-FinOpsCostInsights function
- [ ] [PowerShell] Functions to manage billing permissions
- [ ] [PowerShell] Get-FinOpsRecommendations function
```

```[tasklist]
### PowerShell for FOCUS
- [ ] [PowerShell] ConvertTo-FinOpsSchema function
```

```[tasklist]
### Stretch
```

## 🙋‍♀️ Ask for the community

We'd love to get your feedback! Please leave any questions, comments, or change requests in the release discussions at the bottom of each task list above. We'll try to close each of those out before we finalize the release.
