### ISSUE TITLE
v0.x – 

### ISSUE THREAD

**Issue by bittusakshi** [microsoft/finops-toolkit#448]
## 📝 Scenario
As a **<TODO: What persona is this for?>**, I need to **<TODO: What action does the user need to perform?>** in order to **<TODO: What is the goal? Why is this needed?>**

## 🚀 Goal
TODO: Add a clear and concise description of what people will be able to do when this release is available. Focus on the outcome, not the implementation details. 

## 📋 Tasks

```[tasklist]
### v0.0.0 – TODO: Add focus for sub-release
- [ ] TODO: Add tasks required for each sub-release
- [ ] Address all feedback from the release discussion: #
```

```[tasklist]
### Stretch
- [ ] TODO: Add tasks 
```

## 🙋‍♀️ Ask for the community

We'd love to get your feedback! Please leave any questions, comments, or change requests in the release discussions at the bottom of each task list above. We'll try to close each of those out before we finalize the release.

**Comment by flanakin** [comment]
@bittusakshi Hey, there! I'm assuming this was an accident, so I'll close this out. If you have a question, please post it in [Discussions](https://github.com/microsoft/finops-toolkit/discussions/categories/q-a). If you'd like to report a bug or a feature request, you were in the right place, just select [New issue](https://github.com/microsoft/finops-toolkit/issues/new/choose) and pick either Bug report, Change request, or Feature request, then add the specifics of what you'd like us to do.
