### ISSUE TITLE
🚀 July 2024 (v0.4) release checklist

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#722]
Complete the following tasks to publish a monthly release.

## ✅ Monthly updates

- [x] Update open data files ([learn more](https://github.com/microsoft/finops-toolkit/tree/dev/src/open-data)).
  - [x] Update pricing units:
    - [x] Run the pricing units extraction query.
    - [x] Copy the output and replace the contents of [PricingUnits.csv](https://github.com/microsoft/finops-toolkit/tree/dev/src/open-data)/PricingUnits.csv).
    - [x] Compare changes and revert any removed units. We need to keep all historical units for historical data analysis.
  - [x] Regions
  - [x] Services
  - [x] Update resource types and re-gen internal PowerShell functions:
    ```powershell
    cd "<repo-root>/src/scripts"
    ./Build-OpenData
    ```
  - [x] Consider automating this process in [Build-OpenData](https://github.com/microsoft/finops-toolkit/tree/dev/src/scripts/Build-OpenData.ps1).
- [x] Update Bicep CLI ([docs](https://learn.microsoft.com/azure/azure-resource-manager/bicep/install#azure-cli))
  ```console
  az bicep upgrade
  ```

---

## ✅ Core features

- [x] Review issues and PRs assigned to the [target milestone](https://github.com/microsoft/finops-toolkit/milestones).
  - [x] Create a new milestone for the next monthly release.
  - [x] Move issues that cannot be resolved in time to a new milestone.
  - [x] Submit PRs for issues that can be resolved.
  - [x] Complete [open PRs](https://github.com/microsoft/finops-toolkit/pulls) that are ready to be resolved.
- [x] Confirm there are no pending changes in dev.
  ```powershell
  cd "<repo-root>"
  git checkout dev
  git status
  ```
- [x] Update feature branches and confirm if they're ready for release.
  - [x] Augo-merge feature branch with `dev`:
    ```powershell
    cd "<repo-root>/src/scripts"
    ./Merge-DevBranch *
    ```
  - [x] Manually update remaining feature branches.
    ```powershell
    cd "<repo-root>/src/scripts"
    ./Merge-DevBranch features/<name>
    ```
    - [x] features/exports
    - [x] features/governance
    - [x] features/aoe #775 
    - [x] Commit the changes and push to the feature branch.
  - [x] Build all solutions and confirm all tests pass.
  - [ ] Confirm if all features are code complete and not missing any functionality required for release.
    > _Once in `dev`, the feature is considered part of the next release and can be pushed out at any time. Any broken features will be reverted._
  - [x] Confirm new or updated functionality is documented in the [changelog](https://github.com/microsoft/finops-toolkit/blob/dev/docs/changelog.md).
    > _See [Changelog guidance](#-changelog-guidance) for details about changelog requirements._
  - [x] Confirm new or updated functionality must be documented in the [documentation](https://github.com/microsoft/finops-toolkit/blob/dev/docs).
  - [x] If adding a new tool, update the [list of available tools](https://github.com/microsoft/finops-toolkit/tree/dev/docs#-available-tools) on the documentation home page.
- [x] Merge any feature branches that are ready to `dev`.
  - [x] Create a PR to merge the feature branch into `dev`.
  - [x] Follow the normal PR process to merge the PR.

---

## 🔄️ Finalize release

- [x] Review the [changelog](../docs/_resources/changelog.md) to ensure it encapsulates all changes.
  - [x] Move all released changes to an official numbered version section.
  - [x] If there are committed changes in a feature branch that you want to mention, add them to an "Unreleased" section.
- [x] Update the version.
  ```powershell
  <root>/src/scripts/Update-Version [-Major|Minor|Patch]
  ```
- [x] Build all toolkit templates and resolve any issues.
  > _This step is optional, but can catch issues earlier. You can also add the `-Build` parameter to the publish command in the next step._
  ```powershell
  <root>/src/scripts/Build-Toolkit
  ```
- [x] Ensure all tests pass:
  ```powershell
  <root>/src/scripts/Test-PowerShell
  ```
- Package all release files 
  - [x] Run `Package-Toolkit -Build -PowerBI` script.
  - For each Power BI report:
    - [x] Save the file as a PBIX file to the release folder.
    - [x] Change the sensitivity to **Public**. If the option is disabled, close the file and reopen it.
      > ⚠️ _Power BI does not remember the sensitivity setting for Power BI projects so this needs to be done for each release. If not done, the report will not open for anyone outside of Microsoft._
    - [x] For the Cost summary and Data ingestion reports, remove the following from the Transform data (query editor):
      - [x] Delete both **Recommendations\*** queries.
      - [x] Delete the **InstanceSizeFlexibility** query.
      - [x] Open the **▶️ START HERE** query in the advanced editor and remove connector settings and generated rows in the table from the separator line to the end.
    - [x] For the Cost summary and Commitment discounts reports, remove the following from the Transform data (query editor):
      - [x] Delete all **Hub\*** queries.
    - [x] Save PBIX again in the release folder.
      > ⚠️ _**DO NOT** save the above changes back to the Power BI project files!_
    - [x] Copy the first paragraph from the **Get started** page and export a template (PBIT file) in the release folder. Use the copied text for the description and add "Learn more at https://aka.ms/ftk/{report-name}" as a separate paragraph in the description.
- [ ] ~Check the docs for broken links:~
  - [ ] Create a personal fork of the main repo.
  - [ ] If you already have one, update it to the latest.
  - [ ] Enable GitHub pages in your fork to use the `dev` branch `docs` folder.
  - [ ] Verify the `pages build and deployment` action completes successfully.
  - [ ] Open a dead link checker (e.g., [deadlinkchecker.com](https://www.deadlinkchecker.com/website-dead-link-checker.asp)) and check `https://{your-username}.github.io/finops-toolkit`.
    - [ ] Ignore **link/href** errors for new pages that have not been released in the official `main` branch.
    - [ ] Ignore any **Download** errors for the new release or any new files that haven't been released in the official `main` branch.
    - [ ] Ignore the **Full changelog** error for the new release, which hasn't been released in the official `main` branch.
    - [ ] Ignore the 403 error for learn.finops.org.
    - [ ] Ignore any 429 errors from GitHub. These are caused due to all the contributor links that are checked.
  - [ ] Fix any broken links, push changes, and rerun the tool.

---

## 🔄️ Publish release

- [ ] Submit PRs to publish each template to the target repo.
  > _Bicep modules are published to the Bicep Registry, PowerShell in the PowerShell Gallery, and everything else in the Azure Quickstart Templates. Note that PowerShell is published separately and not included here._
  - [ ] Update your fork and local clone of the target repo (e.g., Bicep Registry or Azure Quickstart Templates).
    > _Make sure you're in the main/master branch of the target repo when publishing a new template. If in another folder, the script will assume you're updating that branch and not create a new one._
  - [ ] Copy template files to the target repo and start a PR:
    ```powershell
    cd <root>/src/scripts
    ./Publish-Toolkit "finops-hub|governance-workbook|optimization-workbook" -Commit
    ```
  - [ ] Open the PR URL from the console and complete the PR template requirements.
    > _If a name hasn't been set, use `New FinOps toolkit template – <template-name>`._
  - [ ] Review the code that's changed in the PR, verify that the changelog covers everything, and update as needed.
  - [ ] If you need to change anything, re-run the publish command without committing:
    ```powershell
    cd <root>/src/scripts
    ./Publish-Toolkit "finops-hub|governance-workbook|optimization-workbook" -Build
    ```
  - [ ] Switch to the target repo folder and verify your changes were applied correctly.
  - [ ] Commit and push your changes.
  - [ ] Return to the PR URL and publish the PR.
  - [ ] Check back after 1 hour to see if there any failed checks.
    - [ ] If there are errors, click the Details link to understand what needs to be fixed.
    - [ ] Fix any issues in the FinOps toolkit codebase (not in the target repo).
    - [ ] Repeat steps 5-9 until all issues have been resolved.
  - [ ] Check back after 2-3 days to see if your PR is completed.
    > _Bicep Registry and Azure Quickstart Template repos are manually reviewed and closed 2-3x per week. If you don't see an update, contact the ARM team._
- [x] Merge to main:
    ```powershell
    cd <root>/src/scripts
    ./Merge-DevBranch main
    ```
- [x] Update the [milestone](https://github.com/microsoft/finops-toolkit/milestones).
  - [x] Review all issues in the milestone, move anything that needs to be pushed, and close any completed items.
  - [x] Close the milestone when all issues have been closed or moved.
- [x] Verify [documentation](https://aka.ms/finops/toolkit) updated correctly.
  > _The documentation site may take 5 minutes to update after the merge is committed. If not updated, look at [GitHub actions](https://github.com/microsoft/finops-toolkit/actions/workflows/pages/pages-build-deployment) to see if there are any failures._
- [x] Tag and publish a [new release](https://github.com/microsoft/finops-toolkit/releases/new):
  - [x] Create a tag on publish using the "vX.X" format.
  - [x] Set the **Target** to `main`.
  - [x] Set the **Previous tag** to the previous release tag.
  - [x] Set the name to `Mmm yyyy (v#.#)`.
  - [x] Copy the body from the previous release to use as a template.
  - [x] Change the "New in" header to use the new version number.
  - [x] Summarize changes from the changelog in the **New in** and **Updated** sections.
    - Simplify to only include one line per tool.
    - Each tool should be linked to its doc page.
    - Don't link features to their respective pages (e.g., PowerShell commands).
    - Don't list every small change. Use "various bug fixes and improvements" to keep it simple.
  - [x] Update the list of direct and indirect contributors.
    - Use the "Generate release notes" feature to get a list of all code contributors.
    - Carefully review the list to ensure everyone is covered since feature branch PRs get merged, which can hide contributors.
    - If they made a code change, add them to the contributor list.
    - If they filed an issue, reviewed a PR, or participated in on- or offline discussions, add them to the list of supporters.
  - [x] Update the discussion and changelog links in the footer. Comment out the AQT link if not ready.
  - [x] Upload all files from the release folder:
    - ZIP files for templates like hubs and workbooks.
    - Power BI PBIX and PBIT files.
    - Open data CSV and JSON files.
    - ZIP file for sample data files.
    - **DO NOT** copy Bicep, PowerShell, PBIP, or image files.
- [x] Update the related discussion with the same text as the release.
- [x] Update all issues to `Status: Released`.

---

## 🔜 Post-release clean-up

- [x] Update the `Toolkit / Should return all known releases` PowerShell integration test based on the latest version.
  > _See `src/powershell/Tests/Integration/Toolkit.Tests.ps1` > `Get-FinOpsToolkitVersion` > `Should return all known releases`_
  - [x] Add the latest public version to the `$expected` variable.
  - [x] Update the file checks to include/exclude any new/removed files.
- [ ] Update remaining branches that were not merged with dev
  - [x] features/mslearn
  - [x] features/services
  - [x] features/ux
  - [ ] features/private
  - [x] features/savings
- [ ] Confirm the following branches are needed or should be deleted:
  - [ ] features/workbookv2
  - [ ] features/powershell
  - [ ] features/hourly

<br>
