### ISSUE TITLE
FOCUS 1.0

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#778]
## 📝 Scenario
As a **FinOps practitioner**, I need to **analyze data using FOCUS 1.0** in order to **leverage existing knowledge**

## 💎 Solution
Update all tools and guidance to leverage FOCUS 1.0.

## 📋 Tasks
```[tasklist]
### Required tasks
- [ ] Add support for FOCUS 1.0 data ingestion in Hubs
- [x] Transform FOCUS 1.0-preview to 1.0 in Hubs Power BI reports
- [x] Transform data to FOCUS 1.0 in the Cost Management connector report
- [x] Document the FOCUS 1.0 metadata
- [x] Update the FOCUS docs to 1.0
- [x] Update the data dictionary to 1.0
```

```[tasklist]
### Stretch goals
- [ ] TODO: Add tasks
```

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.
