### ISSUE TITLE
[Power BI] Add support for raw exports

### ISSUE THREAD

**Issue by flanakin** [microsoft/finops-toolkit#837]
## 📝 Scenario
As a **FinOps practitioner**, I need to **create simple Power BI reports on top of raw Cost Management exports** in order to **share reports with my organization without having to deploy extra resources**

## 💎 Solution
Add support for raw exports to toolkit Power BI reports.

## 📋 Tasks
```[tasklist]
### Required tasks
- [ ] Cost details
- [ ] Reservation recommendations
```

```[tasklist]
### Stretch goals
- [ ] Prices
- [ ] Reservation transactions
- [ ] Reservation details
- [ ] Create a report that uses prices
- [ ] Create a report that uses reservation transactions -- ⚠️ NEED FEEDBACK!
- [ ] Create a report that uses reservation details -- ⚠️ NEED FEEDBACK!
```

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. What reports do you want to see with prices, reservation transactions, or reservation details?
3. Leave comments to help us solidify the vision.
